### ISSUE TITLE
初期表示の月末計算時に OutOfRangeException が発生する

### ISSUE THREAD

**Issue by okadabasso** [ambleside138/TimeRecorder#2]
多分実行時が12月限定だと思いますが以下の部分でOutOfRangeException が発生します

```csharp
 public DateTime EndDate => new DateTime(Year, Month +1, 1).AddDays(-1);
```

例外

> OutOfRangeException
> Year, Month, and Day parameters describe an un-representable DateTime.

**Comment by ambleside138** [comment]
ご指摘ありがとうございます。
このコミット（ bf96f18370981e820bd4c4e9312fd706792c03e6 ）で修正しました

**Comment by okadabasso** [comment]
ありがとうございました
